import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Haywhai App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <h1>this is auth header</h1>
      {children}
      <h1>this is auth footer</h1>
    </div>
  );
}
