import type { Metadata } from "next";
import Navbar from "./shared/layout/navbar";

export const metadata: Metadata = {
  title: "Create Haywhai App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Navbar />
      {children}
      <h1>footer</h1>
    </div>
  );
}
