import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Haywhai App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <h1>this is thr dashboard header</h1>
      {children}
      <h1>this is thr dashboard footer</h1>
    </div>
  );
}
